# Generated by Django 4.2.6 on 2023-10-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuario'), ('invitado', 'Invitado')], max_length=10)),
            ],
        ),
    ]
