# Generated by Django 4.2.7 on 2023-12-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
